@startuml resource-transactions-sequence
skinparam svgDimensionStyle false

participant "Resource Access Provider" as Provider
participant "Resource Consumer" as Consumer


Consumer -> Provider : ITI-19 ATNA Authenticate Node (TLS)
Consumer -> Provider : ITI-71 IUA Get Authorization Token

alt Patient Lookup (identifier known)
    Consumer -> Provider : ITI-78 PDQm Query
else Patient Lookup (demographics only)
    Consumer -> Provider : ITI-119 PDQm $match
end

Consumer -> Provider : IPA Finding and Retrieving Patient Information


@enduml
