@startuml simplified-resource-actors
skinparam svgDimensionStyle false
skinparam AgentPadding 2
skinparam AgentMargin 2
skinparam Padding 2
skinparam nodesep 5
skinparam ranksep 10
skinparam agent {
    MinimumWidth 300
}

skinparam rectangle {
    BackgroundColor White
    BorderColor Black
}



rectangle "Resource Access Provider" as Server {
    agent "Consistent Time - 🕐" as S_CT
    agent "ATNA Secure Node" as S_ATNA
    agent "IUA Authorization Server\n(if internal)" as S_IUAAuth
    agent "PDQm Patient Demographics Supplier" as S_PDQmSrc
    agent " " as S_Hidden1 #White;line:White
    agent "IPA Server" as S_IPAServer
    agent " " as S_Hidden2 #White;line:White
    agent " " as S_Hidden3 #White;line:White

    S_CT -[hidden]down- S_ATNA
    S_ATNA -[hidden]down- S_IUAAuth
    S_IUAAuth -[hidden]down- S_PDQmSrc
    S_PDQmSrc -[hidden]down- S_Hidden1
    S_Hidden1 -[hidden]down- S_IPAServer
    S_IPAServer -[hidden]down- S_Hidden2
    S_Hidden2 -[hidden]down- S_Hidden3
}

rectangle "Resource Consumer" as Client {
    agent "Consistent Time - 🕐" as C_CT
    agent "ATNA Secure Node" as C_ATNA
    agent "IUA Authorization Client" as C_IUAClient
    agent "PDQm Patient Demographics Consumer" as C_PDQm
    agent " " as C_Hidden1 #White;line:White
    agent "IPA Client" as C_IPAClient
    agent " " as C_Hidden2 #White;line:White
    agent " " as C_Hidden3 #White;line:White

    C_CT -[hidden]down- C_ATNA
    C_ATNA -[hidden]down- C_IUAClient
    C_IUAClient -[hidden]down- C_PDQm
    C_PDQm -[hidden]down- C_Hidden1
    C_Hidden1 -[hidden]down- C_IPAClient
    C_IPAClient -[hidden]down- C_Hidden2
    C_Hidden2 -[hidden]down- C_Hidden3
}

S_ATNA <-left- C_ATNA : Secure Communication
S_IUAAuth <-left- C_IUAClient : Authorization Request
S_PDQmSrc <-left- C_PDQm : Patient Id Match
S_IPAServer <-left- C_IPAClient : Query AllergyIntolerance
S_IPAServer <-left- C_IPAClient : Query Condition
S_IPAServer <-left- C_IPAClient : Query Immunization
S_IPAServer <-left- C_IPAClient : Query MedicationRequest
S_IPAServer <-left- C_IPAClient : Query MedicationStatement
S_IPAServer <-left- C_IPAClient : Query Observation


@enduml
